# Generated by Django 2.2.7 on 2019-11-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[(0, 'Owner'), (1, 'User')], max_length=1)),
                ('created_by', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[(0, 'Owner'), (1, 'User')], max_length=1)),
            ],
        ),
    ]
