# Generated by Django 2.2.7 on 2019-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191127_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('User', 'User')], max_length=250),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('User', 'User')], max_length=250),
        ),
    ]
